# Create an index to the harvested files

The XML files contain embedded metadata that includes the name of the prime minister, and the title and date of the transcript. This notebook extracts that metadata from the harvested files and creates a CSV formatted spreadsheet for easy analysis. It also demonstrates some ways of summarising and visualising the metadata.

In [1]:
import os

import altair as alt
import arrow
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.auto import tqdm

## Extract the metadata as save as a CSV

In [2]:
def get_tag(soup, tag):
    """
    Given some Soup, find the specified tag and return its value.
    """
    try:
        value = soup.find(tag).string.strip()
    except AttributeError:
        value = ""
    return value


# Create a list to put the metadata in
all_details = []

# Get the file names of all the harvested files
files = [f for f in os.listdir("transcripts") if f[-4:] == ".xml"]

# Loop through the harvested files
for filename in tqdm(files):

    # Open the file
    with open(os.path.join("transcripts", filename), "rb") as xml_file:

        # Create a dict to put this file's metadata in
        details = {}

        # Load the file contents into Soup and then get the desired tags
        soup = BeautifulSoup(xml_file.read(), features="xml")
        details["id"] = get_tag(soup, "transcript-id")
        details["title"] = get_tag(soup, "title")
        details["pm"] = get_tag(soup, "prime-minister")

        # We're going to reformat the date into the ISO standard, so first get the value
        release_date = get_tag(soup, "field_date")
        try:
            # Then try to parse the date and reformat as ISO
            iso_date = arrow.get(release_date, "DD/MM/YYYY").format("YYYY-MM-DD")
        except arrow.ParserError:
            # If something goes wrong...
            iso_date = ""
        details["date"] = iso_date
        details["release_type"] = get_tag(soup, "release-type")
        details["subjects"] = get_tag(soup, "subjects")
        details["pdf"] = get_tag(soup, "document")

        # Add the metadata for this file to the list
        all_details.append(details)

  0%|          | 0/28560 [00:00<?, ?it/s]

In [3]:
# Convert the metadata to a Pandas dataframe
df = pd.DataFrame(all_details)
df.head()

,id,title,pm,date,release_type,subjects,pdf
0,23830,"Interview with Neil Mitchell, Radio 3AW, Melbo...","Abbott, Tony",2014-09-16,Transcript,Australian Defence Force contribution to inter...,https://pmtranscripts.pmc.gov.au
1,22316,Nuclear Review: Taskforce Membership,"Howard, John",2006-06-07,Media Release,,https://pmtranscripts.pmc.gov.au
2,12395,"Address to the National Seniors Association, M...","Howard, John",2001-05-29,Speech,,https://pmtranscripts.pmc.gov.au
3,2858,DOUBLE TAXATION AGREEMENTS,"Whitlam, Gough",1973-03-20,Media Release,,https://pmtranscripts.pmc.gov.au/sites/default...
4,45673,Radio interview - Triple M Newcastle,"Albanese, Anthony",2024-02-16,Transcript,Prime Minister and Jodie Haydon&#039;s Engagem...,https://pmtranscripts.pmc.gov.au

Save the index as a CSV formatted file.

In [4]:
# Save the metadata as a CSV file
df.to_csv("index.csv", index=False)

## Analyse the metadata

In [5]:
# This loads the metadata from the CSV
# This is not necessary if you've just generated the df
df = pd.read_csv("index.csv", keep_default_na=False)

Let's have a look at the number of transcripts for each Prime Minister.

In [6]:
pm_counts = df["pm"].value_counts().to_frame().reset_index()
pm_counts

                   pm  count
0        Howard, John   5865
1   Albanese, Anthony   3321
2     Morrison, Scott   2427
3       Hawke, Robert   2321
4     Fraser, Malcolm   2080
5      Gillard, Julia   2072
6   Turnbull, Malcolm   1752
7         Rudd, Kevin   1735
8       Keating, Paul   1582
9        Abbott, Tony   1371
10     Whitlam, Gough   1239
11    Menzies, Robert   1207
12       Gorton, John    625
13       Holt, Harold    508
14   McMahon, William    349
15                        75
16       McEwen, John     16
17       Chifley, Ben     11
18       Curtin, John      4

Note that there are 75 transcripts that have no Prime Minister associated with them. We'll exclude those and chart the rest.

In [7]:
df = df.copy().loc[df["pm"] != ""]
pm_counts = df["pm"].value_counts().to_frame().reset_index()

In [8]:
# We're exluding those transcripts where the 'pm' value is empty - df.loc[df['pm'] != '']
alt.Chart(pm_counts.loc[pm_counts["pm"] != ""]).mark_bar().encode(
    # Show number of transcripts on X axis
    x=alt.X("count:Q", title="Number of transcripts"),
    # Show the name of the PM on the Y axis
    y=alt.Y("pm:N", title="Prime Minister"),
    # Show details when you hover
    tooltip=[
        alt.Tooltip("pm:N", title="Prime Minister"),
        alt.Tooltip("count():Q", title="Transcripts"),
    ],
)

alt.Chart(...)

In [9]:
df["year"] = df["date"].str.slice(0, 4).astype("Int64")
# There are some years without records, these will look odd when we chart
# So we'll fill in the blanks
all_years = list(range(df["year"].min(), df["year"].max() + 1))
df_years = pd.DataFrame(all_years, columns=["year"])
df = pd.merge(df, df_years, how="right", on="year")
df.fillna("", inplace=True)

# Get counts by PM and year
pm_year_counts = df.value_counts(["pm", "year"]).to_frame().reset_index()
pm_year_counts

                    pm  year  count
0    Albanese, Anthony  2023    861
1    Albanese, Anthony  2024    855
2       Gillard, Julia  2011    752
3    Turnbull, Malcolm  2017    719
4         Abbott, Tony  2014    718
..                 ...   ...    ...
103    Menzies, Robert  1954      1
104                     1958      1
105    Fraser, Malcolm  1988      1
106      Hawke, Robert  1994      1
107       Howard, John  1995      1

[108 rows x 3 columns]

Let's have a look at the number of transcripts over time.

In [10]:
# Range of years to fill in years with no transcripts
ticks = [t for t in range(1940, 2030, 2)]
# List of PMs used to hide blank records from legend
pms = sorted([p for p in df["pm"].unique() if p])

alt.Chart(pm_year_counts).mark_bar().encode(
    # Year on the X axis
    x=alt.X("year:O").axis(values=ticks),
    # Number of transcripts on the Y axis
    y=alt.Y("count:Q", title="number of transcripts"),
    # Color denotes the PM (names will be in the legend)
    color=alt.Color(
        "pm:N",
        scale=alt.Scale(scheme="tableau20"),
        legend=alt.Legend(title="Prime Minister", values=pms),
    ),
    # Show details on hover
    tooltip=[
        alt.Tooltip("pm:N", title="Prime Minister"),
        alt.Tooltip("year:O", title="Year"),
        alt.Tooltip("count:Q", title="Transcripts"),
    ],
).properties(width=800, padding=20)

alt.Chart(...)

## Release types and subjects

The `release_type` field should tell us what sort of text this transcript represents – interview, media release, etc. Let's see how it's used.

In [11]:
df["release_type"].value_counts()

release_type
Media Release                                10151
Speech                                        5483
Interview                                     5313
Transcript                                    5005
Press Conference                               744
Media statement                                344
Statement in Parliament                        340
Video Transcript                               233
Correspondence                                 131
Broadcast                                      111
Joint Statement                                 87
Opinion                                         67
                                                62
Message                                         54
Index                                           47
Statement                                       46
Doorstop                                        40
Government                                      36
Foreign Affairs                                 16
Education                                       14
Economy &amp; Finance                           14
Arts, Culture &amp; Sport                       13
Health                                          12
Environment                                     12
Communique                                      11
Letter                                          10
Article                                          9
Business &amp; Industry                          9
Defence                                          8
Website Updates                                  7
Blog Transcript                                  6
Security, Law and Justice                        5
Honours, Commemorations &amp; Condolences        5
Remarks                                          5
Press Statement                                  4
Report                                           3
Chat Transcript                                  3
Indigenous Affairs                               3
Foreword                                         2
Immigration                                      2
Trade                                            2
Emergency Management                             2
Employment                                       2
Programme                                        1
Memo                                             1
?                                                1
Communications                                   1
Financial Services                               1
Regional Australia                               1
Broadband                                        1
Climate Change                                   1
Digital Economy                                  1
Workplace Relations                              1
Energy Efficiency                                1
Agriculture                                      1
Social Services                                  1
Budget                                           1
School Education                                 1
Infrastructure &amp; Transport                   1
Message from the PM                              1
Name: count, dtype: int64

Hmmm, so it looks like there's not a lot of control over the values in this field – is a 'Press Statement' the same as a 'Media Release'? It also looks like some subjects have been incorrectly entered here.

By combining `groupby()` and `value_counts()` it's easy to look at the release types for each PM.

In [13]:
pm_type_counts = (
    df.loc[df["pm"] != ""]
    .groupby("pm")["release_type"]
    .value_counts()
    .to_frame()
    .reset_index()
)
pm_type_counts

                 pm   release_type  count
0      Abbott, Tony     Transcript    620
1      Abbott, Tony  Media Release    450
2      Abbott, Tony         Speech    245
3      Abbott, Tony                    41
4      Abbott, Tony        Remarks      5
..              ...            ...    ...
166  Whitlam, Gough      Statement      8
167  Whitlam, Gough     Communique      2
168  Whitlam, Gough         Report      1
169  Whitlam, Gough        Article      1
170  Whitlam, Gough        Message      1

[171 rows x 3 columns]

Because the `release_type` field is a bit of a mess, let's get the top ten release types and visualise them for each PM.

In [14]:
# The index returned by value_counts() are the names of the release types, so we can convert to a list and slice off the first 10.
top_ten_types = (
    df.loc[df["release_type"] != ""]["release_type"].value_counts().index.to_list()[:10]
)

In [15]:
# We're exluding those transcripts where the 'pm' value is empty - df.loc[df['pm'] != '']
alt.Chart(
    pm_type_counts.loc[
        (pm_type_counts["pm"] != "")
        & (pm_type_counts["release_type"].isin(top_ten_types))
    ]
).mark_bar().encode(
    x="count:Q",
    y="pm:N",
    color=alt.Color(
        "release_type:N",
        scale=alt.Scale(scheme="tableau10"),
        legend=alt.Legend(title="release type"),
    ),
).properties(
    width=800, padding=20
)

alt.Chart(...)

In [16]:
df.loc[df["subjects"] != ""].shape

(3024, 8)

In [17]:
len(pd.unique(df["subjects"]))

2806

In [18]:
df["subjects"].value_counts()[:50]

subjects
                                                                                                                                                                                     25466
Federal Budget                                                                                                                                                                          16
Budget 2014.                                                                                                                                                                            14
Same-sex marriage                                                                                                                                                                       14
East Timor                                                                                                                                                                              13
Aboriginal and Torres Strait Islander Voice to Parliament Referendum                                                                                                                    11
Bondi Junction Incident                                                                                                                                                                 11
Voice to Parliament                                                                                                                                                                      8
Bali tragedy                                                                                                                                                                             7
Indigenous Voice to Parliament                                                                                                                                                           7
Australia-China Relationship                                                                                                                                                             6
Budget 2014                                                                                                                                                                              5
National Energy Guarantee                                                                                                                                                                5
New South Wales Floods                                                                                                                                                                   5
Bondi Terror Attack, National Cabinet, Gun Reform                                                                                                                                        5
Bondi Terror Attack                                                                                                                                                                      5
Bali tragedy.                                                                                                                                                                            4
Passing of Her Majesty Queen Elizabeth II                                                                                                                                                4
Cyclone Alfred                                                                                                                                                                           4
Malaysia Airlines tragedy.                                                                                                                                                               3
Australian Defence Force contribution to international coalition against ISIL, visit to Arnhem Land, constitutional recognition for the first Australians.                               3
Malaysia Airlines tragedy                                                                                                                                                                3
Same sex marriage                                                                                                                                                                        3
Citizenship                                                                                                                                                                              3
Federal Budget 2022                                                                                                                                                                      3
Aboriginal and Torres Strait Islander Voice to Parliament referendum                                                                                                                     3
National Cabinet                                                                                                                                                                         3
Simon Crean, Russia, Voice to Parliament                                                                                                                                                 3
Garma Festival, Voice to Parliament                                                                                                                                                      3
Wakeley Church Incident, Bondi Junction Incident                                                                                                                                         3
Australia-Indonesia Relations                                                                                                                                                            3
Australia to Recognise Palestinian State                                                                                                                                                 3
Tropical Cyclone Alfred                                                                                                                                                                  3
Middle East Conflict                                                                                                                                                                     3
Royal Commission on Antisemitism and Social Cohesion                                                                                                                                     3
Zimbabwe                                                                                                                                                                                 2
G20                                                                                                                                                                                      2
Malaysia Airlines Flight MH17                                                                                                                                                            2
Flight MH370.                                                                                                                                                                            2
Malaysia Airlines Flight MH17.                                                                                                                                                           2
Malaysia Airlines Flight MH17, Operation Sovereign Borders.                                                                                                                              2
Australian Defence Force contribution to international coalition against ISIL.                                                                                                           2
Qantas.                                                                                                                                                                                  2
International supply mission to Iraq                                                                                                                                                     2
Joint Counter Terrorism Team Operation.                                                                                                                                                  2
G20 volunteer launch, G20 Summit, Malaysia Airlines flight MH17, World infrastructure hub, ACOSS report, school curriculum, Ebola, China’s coal tariff, Brisbane transport video.        2
Budget 2014, Federation white paper.                                                                                                                                                     2
Anzac Day commemorations.                                                                                                                                                                2
Australians facing execution in Indonesia.                                                                                                                                               2
Meeting of the Council of Australian Governments.                                                                                                                                        2
Name: count, dtype: int64

----
Created by [Tim Sherratt](https://timsherratt.au) for the [GLAM Workbench](https://glam-workbench.net)